env:
  global:
    - secure: MLB4OdsJJe/B+7ufL/v+7ZPOQlYNCZ60Zi/Vwpu9IVPZE/TQ0GN0Hh4mfVlXlP59XC9+vZ9OtHOcwGtWSWhEEa0PUD4dwphrOuI9PQPZ+fsOnY0zxfubaiK3Apx4b3AkErmdscp5/LHp2AQQ8RrBcvejzFN6zJs6G+M6kKKNFNE=
before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - yes | sudo add-apt-repository ppa:cmrx64/cargo
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly cargo
script:
  - cargo build
  - rustc --test src/spellck.rs -o tester
  - ./tester
  - rustdoc -o doc src/spellck.rs
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
